### ISSUE TITLE
Date in listDateDisabled, still able to select 

### ISSUE THREAD

**Issue by peterlau0010** [benznest/flutter_rounded_date_picker#15]
flutter_rounded_date_picker: 1.0.4

 25-Mar is in listDateDisabled, it should not be able to select. 

![flutter_17](https://user-images.githubusercontent.com/9346306/77335621-5abfdc80-6d61-11ea-8a61-2e21af4290ad.png)
![flutter_18](https://user-images.githubusercontent.com/9346306/77335638-61e6ea80-6d61-11ea-80e4-076bd508a72a.png)

[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.1 19B88, locale en-GB)
    • Flutter version 1.15.17 at /Applications/flutter
    • Framework revision 2294d75bfa (2 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

**Comment by heshesh2010** [comment]
me too

**Comment by heshesh2010** [comment]
you can use this :

  show(context) async {
    DateTime newDateTime = await showRoundedDatePicker(
        context: context,
        listDateDisabled: [
          DateTime.now().subtract(Duration(days: 2)),
          DateTime.now().subtract(Duration(days: 4)),
          DateTime.now().subtract(Duration(days: 6)),
          DateTime.now().subtract(Duration(days: 8)),
          DateTime.now().subtract(Duration(days: 10)),
          DateTime.now().add(Duration(days: 2)),
          DateTime.now().add(Duration(days: 4)),
          DateTime.now().add(Duration(days: 6)),
          DateTime.now().add(Duration(days: 8)),
          DateTime.now().add(Duration(days: 10)),
        ],
        onTapDay: (DateTime dateTime, bool available) {
          if (!available) {
            showDialog(
                context: context,
                builder: (c) => CupertinoAlertDialog(
                      title: Text("هذا الموعد محجوز من مستأجر اخر"),
                      actions: <Widget>[
                        CupertinoDialogAction(
                          child: Text("حسناً"),
                          onPressed: () {
                            Navigator.pop(context);
                          },
                        )
                      ],
                    ));
          }
          return available;
        },
        theme: ThemeData(primarySwatch: Colors.green),
        builderDay: (DateTime dateTime, bool isCurrentDay, bool isSelected,
            TextStyle defaultTextStyle) {
          if (isSelected) {
            return Container(
              decoration: BoxDecoration(
                  color: Colors.orange[600], shape: BoxShape.circle),
              child: Center(
                child: Text(
                  dateTime.day.toString(),
                  style: defaultTextStyle,
                ),
              ),
            );
          }

          if (dateTime.day == 10) {
            return Container(
              decoration: BoxDecoration(
                  border: Border.all(color: Colors.pink[300], width: 4),
                  shape: BoxShape.circle),
              child: Center(
                child: Text(
                  dateTime.day.toString(),
                  style: defaultTextStyle,
                ),
              ),
            );
          }
          if (dateTime.day == 12) {
            return Container(
              decoration: BoxDecoration(
                  border: Border.all(color: Colors.pink[300], width: 4),
                  shape: BoxShape.circle),
              child: Center(
                child: Text(
                  dateTime.day.toString(),
                  style: defaultTextStyle,
                ),
              ),
            );
          }

          return Container(
            child: Center(
              child: Text(
                dateTime.day.toString(),
                style: defaultTextStyle,
              ),
            ),
          );
        });
  }

**Comment by benznest** [comment]
Fixed this issue in version 1.0.5
