### ISSUE TITLE
Cancel doesn't return null

### ISSUE THREAD

**Issue by GrbavaCigla** [benznest/flutter_rounded_date_picker#37]
When I use `showRoundedDatePicker` and click on the cancel button instead of null, I get current date.

**Comment by benznest** [comment]
Thanks for your feedback.
the bug is fixed, Please try version 2.0.1

**Comment by GrbavaCigla** [comment]
Thanks for your efforts :D

**Comment by haizadvnet** [comment]
This update gives issue such as
``` NoSuchMethodError (NoSuchMethodError: The getter 'weekday' was called on null.``` once I cancelled the dialog. So I need to check for nulable value.
```
 DateTime newDateTime =
     await showRoundedDatePicker(
        context: context,
        initialDate: DateTime.now(),
        firstDate: DateTime(DateTime.now().year - 1),
        theme: ThemeData(primarySwatch: Colors.purple),
 ) ?? DateTime.now();
```
