### ISSUE TITLE
Errors with Flutter 3.3 due to deprecations

### ISSUE THREAD

**Issue by vitalsh** [benznest/flutter_rounded_date_picker#53]
A number of deprecations have been removed in Flutter 3.3
Foe example: FlatButton
(in release notes: Remove deprecated FlatButton by @Piinks in https://github.com/flutter/flutter/pull/98545)

Getting this error when trying to compile with Flutter 3.3:
Error: The method 'FlatButton' isn't defined for the class 'FlutterRoundedButtonAction'.

**Comment by stefan-weinand** [comment]
I replaced FlatButton by TextButton in the source code as described here:
[https://docs.flutter.dev/release/breaking-changes/buttons](https://docs.flutter.dev/release/breaking-changes/buttons)

**Comment by vitalsh** [comment]
Super !
Thanks for the fast reaction ;)
