### ISSUE TITLE
New classes for v1.0 cannot be imported

### ISSUE THREAD

**Issue by Dimarv135** [benznest/flutter_rounded_date_picker#6]
MaterialRoundedDatePickerStyle and MaterialRoundedYearPickerStyle cannot be resolved. I have to manually add them in rounded_picker.dart generated file in order for the IDE (Android studio) to recognise them.

**Comment by benznest** [comment]
try import manually.
`import 'package:flutter_rounded_date_picker/src/material_rounded_date_picker_style.dart';
import 'package:flutter_rounded_date_picker/src/material_rounded_year_picker_style.dart';`

**Comment by Dimarv135** [comment]
Yes that works, but you shouldn't import files directly from another package.

**Comment by mauro1998** [comment]
Same issue here.
