### ISSUE TITLE
Current day highlight issue

### ISSUE THREAD

**Issue by praveenpke** [benznest/flutter_rounded_date_picker#8]
in my case initial date is yesterday, but how do i highlight todays date even though it is disabled
. Todays date is feb 21 i want it disabled but highlighted 
<img width="244" alt="Screen Shot 2020-02-21 at 11 28 46 AM" src="https://user-images.githubusercontent.com/35184782/75056824-5cb22980-549d-11ea-9714-7448a086a6d9.png">

**Comment by benznest** [comment]
Fixed this issue in version 1.0.5
