### ISSUE TITLE
date picker height and width - how to adjust based on screen sizes

### ISSUE THREAD

**Issue by praveenpke** [benznest/flutter_rounded_date_picker#9]
<img width="402" alt="Screen Shot 2020-02-21 at 12 39 33 PM" src="https://user-images.githubusercontent.com/35184782/75061890-47da9380-54a7-11ea-8aff-9a52d6287c07.png">
<img width="344" alt="Screen Shot 2020-02-21 at 12 39 49 PM" src="https://user-images.githubusercontent.com/35184782/75061893-490bc080-54a7-11ea-9c74-e249b91c320c.png">

**Comment by Dimarv135** [comment]
Having the same issue with Tablet/Web format. This wasn't existent in v0.3.

**Comment by deadsoul44** [comment]
Did you find a solution?

**Comment by jegerima** [comment]
For the versión 1.0.4 I've edited the class _FlutterRoundedDatePickerDialog_ at the line 262
 
I replaced this:
`Flexible(child: picker)`

with a SizedBox:
`SizedBox(height: 320, child: picker)`

It's a workaround, and 320 pixels work for me.
Te expanded behavior is caused by that child, I think.

**Comment by benznest** [comment]
Sorry, I am late with this problem. 
now version 1.0.5 

you can use Height for date picker.
`                    DateTime newDateTime = await showRoundedDatePicker(
                      context: context,
                      ...
                      height: 320,
                    );`

**Comment by elenapolyakova** [comment]
Doesn't work with landscape orientation :(

**Comment by prawproudd** [comment]
It doesn't work with the web format.(package version 1.0.5)

**Comment by NachiketGohil** [comment]
You can Just use it's Height attribute...
this worked for me =>
```
final DateTime pickedFrom = await showRoundedDatePicker(
  height: 300,
)
```
